package detector

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"slices"
	"strings"
	"testing"

	"github.com/step-security/dev-machine-guard/internal/detector/configaudit"
	"github.com/step-security/dev-machine-guard/internal/model"
)

// The shared contract is generated by the real guarded scanner over synthetic
// files. Only the temporary home and the IDs derived from it are normalized.
func TestComposerGoldenProducer(t *testing.T) {
	if runtime.GOOS == model.PlatformWindows {
		t.Skip("canonical Unix fixture; wire round-trip and scanner tests also run on Windows")
	}
	home := goTestHome(t)
	root := filepath.Join(home, "code")
	app := filepath.Join(root, "app")
	composerWriteProject(t, app)
	goWrite(t, filepath.Join(app, "composer.json"), `{"name":"example/app","version":"dev-main","require":{"example/lib":"^2"},"require-dev":{"example/dev":"^1"},"config":{"disable-tls":true,"secure-http":false,"allow-plugins":true,"source-fallback":false,"lock":false,"http-basic":{"CANARY_HOST":{"password":"CANARY_PASSWORD"}}},"repositories":{"CANARY_REPOSITORY_NAME":{"type":"composer","url":"http://user:CANARY_PASSWORD@repo.example.invalid/index?CANARY_QUERY#CANARY_FRAGMENT","canonical":false,"only":["example/*"]},"packagist.org":false}}`, 0o600)
	goWrite(t, filepath.Join(app, "composer.lock"), `{"packages":[{"name":"example/lib","version":"2.1.0","source":{"type":"git","url":"https://user:CANARY_PASSWORD@github.com/example/lib.git?CANARY_QUERY","reference":"release/2.1"},"dist":{"type":"zip","url":"https://dist.example.invalid/lib.zip?CANARY_QUERY","reference":"release/2.1","shasum":"0123456789abcdef0123456789abcdef01234567"}},{"name":"example/transitive","version":"1.0.0","dist":{"type":"zip","url":"https://dist.example.invalid/transitive.zip","shasum":"CANARY_INVALID_HASH"}}],"packages-dev":[{"name":"example/dev","version":"1.1.0"}]}`, 0o600)
	goWrite(t, filepath.Join(app, "vendor", "composer", "installed.json"), `{"packages":[{"name":"example/lib","version":"1.9.0","version_normalized":"1.9.0.0","type":"library","install-path":"../example/lib"},{"name":"example/missing","version":"dev-feature","install-path":"../example/missing"},{"name":"example/meta","version":"1.0.0","type":"metapackage","install-path":null},{"name":"example/local","version":"dev-main","type":"library","dist":{"type":"path","url":"../../local","reference":"local-reference"},"install-path":"../example/local"}],"dev-package-names":[]}`, 0o600)
	goWrite(t, filepath.Join(home, "local", "marker"), "", 0o600)
	global := filepath.Join(home, ".composer")
	goWrite(t, filepath.Join(global, "composer.json"), `{"require":{"example/tool":"^1"}}`, 0o600)
	goWrite(t, filepath.Join(global, "config.json"), `{"config":{"store-auths":"prompt","preferred-install":{"*":"dist"},"audit":{"abandoned":"report"},"policy":{"malware":{"block":true,"audit":"fail","block-scope":"all"},"ignore-unreachable":["audit"]}}}`, 0o600)
	goWrite(t, filepath.Join(global, "auth.json"), `{"CANARY_AUTH_FILE":"CANARY_SECRET"}`, 0o600)
	goWrite(t, filepath.Join(global, "vendor", "composer", "installed.json"), `[{"name":"example/tool","version":"v1.0.0","type":"library","target-dir":"Legacy"}]`, 0o600)
	goWrite(t, filepath.Join(root, "orphan", "composer", "installed.json"), `{"packages":[{"name":"example/orphan","version":"dev-main","type":"custom-installer"},{"name":"invalid"}],"dev-package-names":[]}`, 0o600)
	scanner, x := composerTestScanner(t, home)
	x.env["COMPOSER_AUTH"] = "CANARY_PROCESS_AUTH"
	x.env["HTTPS_PROXY"] = "https://user:CANARY_PASSWORD@proxy.example.invalid:8443/?CANARY_QUERY#CANARY_FRAGMENT"
	x.env["NO_PROXY"] = "localhost,.example.invalid"
	inv, audit := scanner.Scan(context.Background(), goTestTarget(home), []string{root}, nil)
	composerAssertRefs(t, inv, audit)
	type sections struct {
		Inventory *model.ComposerInventory   `json:"composer_inventory"`
		Audit     *model.ComposerConfigAudit `json:"composer_config_audit"`
	}
	pair := sections{inv, audit}
	raw, err := json.Marshal(pair)
	if err != nil {
		t.Fatal(err)
	}
	raw = bytes.ReplaceAll(raw, []byte(home), []byte("/home/composer-fixture"))
	if err := json.Unmarshal(raw, &pair); err != nil {
		t.Fatal(err)
	}
	replacements := []string{}
	for _, s := range pair.Inventory.Sources {
		replacements = append(replacements, s.SourceID, configaudit.GoSourceID(goTestTarget(home).Username, s.Kind, s.Path))
	}
	for _, f := range pair.Audit.Files {
		replacements = append(replacements, f.SourceID, configaudit.GoSourceID(goTestTarget(home).Username, "composer_config_"+f.Scope, f.Path))
	}
	raw = []byte(strings.NewReplacer(replacements...).Replace(string(raw)))
	if err := json.Unmarshal(raw, &pair); err != nil {
		t.Fatal(err)
	}
	for i := range pair.Inventory.Sources {
		slices.Sort(pair.Inventory.Sources[i].DiscoveredSources)
	}
	slices.SortFunc(pair.Audit.Findings, func(a, b model.CargoConfigFinding) int {
		return strings.Compare(a.Code+a.SourceID+a.Key, b.Code+b.SourceID+b.Key)
	})
	composerAssertRefs(t, pair.Inventory, pair.Audit)
	raw, err = json.MarshalIndent(pair, "", "  ")
	if err != nil {
		t.Fatal(err)
	}
	raw = append(raw, '\n')
	if bytes.Contains(raw, []byte("CANARY_")) {
		t.Fatal("fixture contains a credential canary")
	}
	path := "../model/testdata/composer_inventory_v1_golden.json"
	if os.Getenv("UPDATE_COMPOSER_GOLDEN") == "1" {
		if err := os.WriteFile(path, raw, 0o600); err != nil {
			t.Fatal(err)
		}
	}
	want, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(raw, want) {
		t.Fatal("producer differs from shared Composer golden; review the contract before regenerating")
	}
}
